name: bookstore
description: Music Database for AMSE Project n1
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  adaptive_navigation: ^0.0.3
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  # analysis_defaults:
  #   path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
  - lib\src\data\covers\Black_Holes_and_Revelations.jpg
  - lib\src\data\covers\Chromakopia.jpg
  - lib\src\data\covers\Flying_Beagle.jpg
  - lib\src\data\covers\Focus.jpg
  - lib\src\data\covers\GNX.jpg
  - lib\src\data\covers\Hurry_Up_Tomorrow.jpg
  - lib\src\data\covers\Loud.jpg
  - lib\src\data\covers\Madvillainy.jpg
  - lib\src\data\covers\Starboy.jpg
  - lib\src\data\covers\Teens_Of_Denial.jpg
  - lib\src\data\covers\The_Resistance.jpg
  - lib\src\data\covers\To_Pimp_A_Butterfly.jpg
